<%@ Page Title="About" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="About.aspx.vb" Inherits="dimoskopisi.About" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <h4>Περί του τμήματος</h4>
    <p><span style="color: rgb(85, 85, 85); font-family: 'Segoe UI Light', sans-serif; font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 24px; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Η Διεύθυνση πληροφορικής της 7ης Υγειονομικής Περιφέρειας, από το 2002, σχεδιάζει, αναπτύσσει και προσπαθεί, προς την κατεύθυνση της ενσωμάτωσης της πληροφορικής στο χώρο της υγείας. Έτσι, συμμετείχε και βοήθησε πολλές καινοτόμες δράσεις, ώστε να θεωρείται η Κρήτη από τις υγειονομικές περιφέρειες, με τη μεγαλύτερη εξάπλωση πληροφοριακών συστημάτων στην Ελλάδα. Η προσπάθεια συνεχίζεται...</span></p>
    <p>&nbsp;</p>
    <p><b style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(51, 51, 51);">Διεύθυνση</b><span style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(51, 51, 51);">: Σμύρνης 26, ΤΚ 71201, Τ.Θ. 1285, Ηράκλειο Κρήτης</span></p>
    <p><b style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(51, 51, 51);">Τηλεφωνικό κέντρο</b><span style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(51, 51, 51);">: +30-2813 404400</span></p>
    <p><b style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(51, 51, 51);">Κεντρικό fax</b><span style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(51, 51, 51);">: +30-2810 331570</span></p>
    <p><b style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(51, 51, 51);">Κεντρικό emaill</b><span style="color: rgb(255, 255, 255); font-family: 'Segoe UI Light', sans-serif; font-size: small; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(51, 51, 51);"><a href="mailto:info@hc-crete.gr">: info@hc-crete.gr</a></span></p>
    <p>&nbsp;</p>
    
<h4>Συντελεστές</h4>
        <br />
    <h5>
        Αρχική Ιδέα: Μοσχοβάκης Γιώργος<br />
        Προγραμματισμός: Μοσχοβάκης Γιώργος, Καρέλης Σταύρος<br />
        Σχεδιασμός: Μοσχοβάκης Γιώργος, Καρέλης Σταύρος<br />
        Σχεδιασμός βάσης δεδομένων: Μοσχοβάκης Γιώργος, Καρέλης Σταύρος<br />
        Εμπλουτισμός ιδέας: Μοσχοβάκης Γιώργος, Μαλάς Κώστας, Καρέλης Σταύρος<br />
        Beta testers: Μοσχοβάκης Γιώργος, Καρέλης Σταύρος<br />
    </h5>
       
</asp:Content>
